name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  commit:
    name: Commit Lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}    
    outputs: 
      version: ${{ steps.semver.outputs.version }}
      tag: ${{ steps.semver.outputs.tags }}    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x
    - name: Install Packages
      run: npm install
    - name: Check Commit Message
      uses: "cdotyone/github-commit-lint@main"
      with:
        message: "${{github.event.head_commit.message}}"

  prepare:
    name: Create dist
    runs-on: ubuntu-latest
    container: node:12
    strategy:
      matrix:
        lambda: ["modules/webhook/lambdas/webhook", "modules/runner-binaries-syncer/lambdas/runner-binaries-syncer", "modules/runners/lambdas/runners"]
    steps:
      - name: Extract lambda name
        id: lambda
        env:
          LAMBDA: ${{ matrix.lambda }}
        run: echo ::set-output name=name::${LAMBDA##*/}
      - uses: actions/checkout@v2
      - name: Add zip
        run: apt update && apt install zip
      - name: Build dist
        working-directory: ${{ matrix.lambda }}
        run: yarn install && yarn run test && yarn dist
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.lambda.outputs.name }}
          path: ${{ matrix.lambda }}/${{ steps.lambda.outputs.name }}.zip
          retention-days: 1

  release:
    name: Release
    needs: [commit, prepare]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x
    - name: Install Packages
      run: npm install
    - name: Conventional Changelog Action
      uses: cdotyone/conventional-changelog-action@v3.9.0
      with:
        github-token: ${{ github.token }}
        tag-prefix: 'v'
        release-count: '20'
        version-file: './version.json'
